services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/spotify_player
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=spotify_player
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Service for running drizzle-kit commands
  drizzle:
    build:
      context: .
      target: deps # Use the deps stage to have all dependencies installed
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/spotify_player
    depends_on:
      - db
    # This service doesn't start automatically, it's used for running commands
    profiles:
      - tools
    # Example commands:
    # docker compose run drizzle npm run db:generate
    # docker compose run drizzle npm run db:migrate
    # docker compose run drizzle npm run db:studio

volumes:
  postgres_data:
  node_modules:
