name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.test
          tags: spotify-player-test:latest
          outputs: type=docker,dest=${{ runner.temp }}/spotify-player-test.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: spotify-player-test
          path: ${{ runner.temp }}/spotify-player-test.tar

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: spotify-player-test
          path: ${{ runner.temp }}

      - name: Load image
        run: |
          docker load --input ${{ runner.temp }}/spotify-player-test.tar
          docker image ls -a

      - name: Run tests
        run: docker run --rm spotify-player-test:latest npm test

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: spotify-player-test
          path: ${{ runner.temp }}

      - name: Load image
        run: |
          docker load --input ${{ runner.temp }}/spotify-player-test.tar
          docker image ls -a

      - name: Run linting
        run: docker run --rm spotify-player-test:latest npm run lint

  type-check:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: spotify-player-test
          path: ${{ runner.temp }}

      - name: Load image
        run: |
          docker load --input ${{ runner.temp }}/spotify-player-test.tar
          docker image ls -a

      - name: Run type checking
        run: docker run --rm spotify-player-test:latest npm run type:check
